#!/bin/bash

main() {
  readonly TITLE=demo-06

  readonly IMAGE=eightycolumns/csound:${TITLE}
  readonly WORKDIR=/home/csound/${TITLE}

  docker run --rm -v "${PWD}:${WORKDIR}" -w "${WORKDIR}" "${IMAGE}" make
}

[ "${BASH_SOURCE[0]}" == "$0" ] && main "$@"
